### ISSUE TITLE
收取验证码后，点击前盘上的提示直接输入，回调会执行两次

### ISSUE THREAD

**Issue by huofuyan** [CRAnimation/CRBoxInputView#17]
textDidChangeblock; 这个回调会执行两次

**Comment by BearRan** [comment]
请尝试在Demo中测试是否有这个问题。如果有，可以重新开启issuse

**Comment by xfdev** [comment]
我也遇到这个问题了：
CRBoxInputView.m 文件中
`- (void)textDidChange:(UITextField *)textField`
这个方法会被执行两遍，两遍中 textField.text 的值是一样的，最后就导致 isFinished 的回调执行两遍，但是在 demo 中未发现这个问题，使用的是 InputView_line 的输入框，修改demo中创建输入框的代码为我项目中代码，也未能复现这个问题。
最后在源码中加入这个判断解决了问题：
```
- (void)textDidChange:(UITextField *)textField{
    UITextRange *selectedRange = [textField markedTextRange];
    if (!selectedRange || selectedRange.empty) {
        // 原有代码放这里
    }
}
```
