### ISSUE TITLE
pod 安装失败，

### ISSUE THREAD

**Issue by melovegithub** [CRAnimation/CRBoxInputView#2]
pod 安装失败， [!] Unable to find a specification for `CRBoxInputView`

**Comment by BearRan** [comment]
执行`pod update`试一下

**Comment by melovegithub** [comment]
> 执行`pod update`试一下

还是不行，、

**Comment by BearRan** [comment]
那你再试下下面的方法
方法一
`pod repo update`
`pod install`

方法二
`pod repo remove master`
`pod setup`
参考链接[https://blog.csdn.net/u011439689/article/details/81129313](https://blog.csdn.net/u011439689/article/details/81129313)
