### ISSUE TITLE
倒计时按钮在diss控制器时定时器没有销毁造成内存泄漏

### ISSUE THREAD

**Issue by LayChan** [CRAnimation/CRBoxInputView#21]

**Comment by BearRan** [comment]
所以这个问题是存在还是不存在？

**Comment by LayChan** [comment]
不存在

发自我的 iPhone

在 2019年7月24日，13:21，Bear <notifications@github.com<mailto:notifications@github.com>> 写道：


所以这个问题是存在还是不存在？
