### ISSUE TITLE
cellProperty.showLine = YES 

### ISSUE THREAD

**Issue by pttyy** [CRAnimation/CRBoxInputView#22]
下划线风格时，希望也添加一个下划线的 选中和未选中 状态

**Comment by BearRan** [comment]
你好，现已增加该功能。请更新至v1.1.2即可
`cellProperty.customLineViewBlock = ^CRLineView * _Nonnull{
        CRLineView *lineView = [CRLineView new];
        lineView.underlineColorNormal = color_master;
        lineView.underlineColorSelected = [color_master colorWithAlphaComponent:0.55];
        [lineView.lineView mas_remakeConstraints:^(MASConstraintMaker *make) {
            make.height.mas_equalTo(4);
            make.left.right.bottom.offset(0);
        }];

        return lineView;
    };`

**Comment by BearRan** [comment]
你好，现已增加该功能。请更新至v1.1.2即可。请参考下面属性来使用。
`lineView.underlineColorNormal = color_master;`
`lineView.underlineColorSelected = [color_master colorWithAlphaComponent:0.55];`
