### ISSUE TITLE
iOS11以上，从键盘上直接点击验证码输入的时候会触发两次回调

### ISSUE THREAD

**Issue by iOSxiaoge** [CRAnimation/CRBoxInputView#24]

**Comment by BearRan** [comment]
这个情况，在Demo中运行时会出现吗？

**Comment by iOSxiaoge** [comment]
demo没法测试接收验证码，我加你QQ了

**Comment by YoungLeung** [comment]
我也出现了这个情况 走了两次回调

**Comment by BearRan** [comment]
Mac打开iMessage，然后你把之前的验证码短信转发到自己的手机号，就可以了。如果还不行，加我微信，RANRAN1201，QQ不常用了。最近在找工作，有点忙，回复不及时，请见谅。

**Comment by BearRan** [comment]
同学们，由于有很多人反馈过这个问题。鄙人也尝试过去修复，但由于我的设备（iOS12.1）无法复现这个问题，所以一直找不到根本原因。
鄙人现在加了个判断，如果字符长度发生变化，才会触发block回调。
请大家更新到v1.1.3版本，如果依然存在这个问题，请Reopen这个issuse，后续鄙人会跟进。同时也期待小伙伴能一起加入解决这些让人迷惑的bug。

**Comment by xfdev** [comment]
我的是 iOS 12.3.1 也会触发两次回调，新版本未测试
