### ISSUE TITLE
list模式下，布局变成上下的四宫格布局

### ISSUE THREAD

**Issue by CoderWeiLee** [CRAnimation/CRBoxInputView#25]
swift编写

**Comment by BearRan** [comment]
有具体的代码可以贴出来吗？

**Comment by CoderWeiLee** [comment]
解决了 是itemSize设置的高度 和 inputView设置的高度不一致引起的，谢谢哦。 我还特地发了邮件给你

**Comment by BearRan** [comment]
好的。看来文档还有需要改进的地方。因为itemSize会和collectionViewLayout挂钩，inputView的尺寸其实又是相对独立的。一直在思考这个我应该怎么表述。如果有好的建议，欢迎分享。可以避免后面的小伙伴出现同样的困惑。
