### ISSUE TITLE
建议可使用自定义inputview

### ISSUE THREAD

**Issue by Jean1992** [CRAnimation/CRBoxInputView#26]
可以像UITextfield那样设置inputview

**Comment by Jean1992** [comment]
像这样，在"CRBoxTextView.h"文件里添加

`@property (nullable, readwrite, strong) UIView *inputView;`

在"CRBoxTextView.m"文件里添加

```objective-C
- (void)setInputView:(UIView *)inputView {
    _inputView = inputView;
    self.textView.inputView = inputView;
}

**Comment by BearRan** [comment]
self.textView指的是什么呢？

**Comment by Jean1992** [comment]
> self.textView指的是什么呢？

那是你的代码😂

**Comment by BearRan** [comment]
可否加个QQ？648070256

**Comment by Jean1992** [comment]
> 可否加个QQ？648070256

加了

**Comment by BearRan** [comment]
你好，更新了。更新到v1.1.5即可使用
