### ISSUE TITLE
下划线的阴影在哪里影藏？

### ISSUE THREAD

**Issue by xiangleiios** [CRAnimation/CRBoxInputView#27]
没有看到下划线阴影的熟悉

**Comment by BearRan** [comment]
CRLineView里面的lineView属性可以直接操作的。
`cellProperty.customLineViewBlock = ^CRLineView * _Nonnull{
        CRLineView *resLineView = [CRLineView new];
        resLineView.lineView.layer.shadowOpacity = 0;

        return resLineView;
    };`
