### ISSUE TITLE
在XR真机上发生闪退

### ISSUE THREAD

**Issue by CoderWeiLee** [CRAnimation/CRBoxInputView#28]
<img width="829" alt="截屏2019-11-28下午5 04 52" src="https://user-images.githubusercontent.com/19401955/69793041-ae327b80-1202-11ea-9049-7e2538ce22dd.png">

请问下有什么好的解决办法吗

**Comment by BearRan** [comment]
老哥，你这个好像是pod的问题。库没加载上。删掉重新加一下？
