### ISSUE TITLE
无法回退

### ISSUE THREAD

**Issue by YangYueFan** [CRAnimation/CRBoxInputView#3]
就是输入到第N个时  发现输出时，无法编辑前面输入的

**Comment by BearRan** [comment]
1，“ 发现输出时，无法编辑前面输入的”这句话不太理解你的意思。
2，删除，是只能从后往前依次删除的。不能从中间开始删除或者编辑的。
3，如果你说的是从中间删除的需求，以后版本可能会加上该功能。或者你也可以在该pod基础上增加这个功能，并提交pull request。
