### ISSUE TITLE
建议新增修改密码的功能

### ISSUE THREAD

**Issue by snakeJudy** [CRAnimation/CRBoxInputView#31]
修改密码需要实现：
1、默认显示已存在的密码。
2、当开始编辑时，自动清空掉旧密码

**Comment by BearRan** [comment]
你好，该功能已增加。如果觉得好用，有劳给个Star。谢谢。
![image](https://user-images.githubusercontent.com/11605807/72712258-9eea0180-3ba5-11ea-89ec-8a7ed41c5cfb.png)
