### ISSUE TITLE
可否支持可变位数的密码

### ISSUE THREAD

**Issue by snakeJudy** [CRAnimation/CRBoxInputView#33]
比如，密码位数为4-8位，我设置的codelength为最大值8，但是会出现当使用ifClearAllInBeginEditing和reloadInputString时，如果密码为6位，当我开始编辑的时候，并未自动clearall。textFieldDidBeginEditing中是否可以不依赖于codelength去做cleaerAll的动作。

**Comment by BearRan** [comment]
现已增加修改codeLength的方法，更新到v1.2.0即可使用
[ResetCodeLength说明](https://github.com/CRAnimation/CRBoxInputView#Anchor_ResetCodeLength)
`[boxInputView resetCodeLength:_boxInputView.codeLength+1 beginEdit:YES];`
