### ISSUE TITLE
佬板敢不敢支持ios8

### ISSUE THREAD

**Issue by crazypoo** [CRAnimation/CRBoxInputView#5]

**Comment by BearRan** [comment]
没有8的设备了。。。不知道会不会有bug。那我晚上更新一版，有bug的话你反馈一下。

**Comment by crazypoo** [comment]
试过了,没bug

**Comment by BearRan** [comment]
好，稍等，弄好了我回复你。

**Comment by crazypoo** [comment]
还是不行,我看了看,4个就没问题,6个就有问题了
2019-01-17 12:54:01.899 CRBoxInputView_Example[937:498758] *** Terminating app due to uncaught exception 'NSRangeException', reason: '*** -[__NSArrayM objectAtIndex:]: index 4 beyond bounds [0 .. 3]'

**Comment by BearRan** [comment]
晚上试一下，有其他问题可以一并发上来。

**Comment by crazypoo** [comment]
小屏幕的时候,界面有点挤而已

**Comment by BearRan** [comment]
可以通过`boxInputView.boxFlowLayout.itemSize = CGSizeMake(50, 50);`设置cell的尺寸。看了文档还要修改，这个不明显

**Comment by BearRan** [comment]
已支持iOS8，更新到0.1.3版本即可。

**Comment by BearRan** [comment]
更新后执行下'shift + comand +k',清空下编译的缓存。有个文件的路径我换了，clean一下才能正常编译。

**Comment by crazypoo** [comment]
厉害厉害

**Comment by crazypoo** [comment]
好了,我来反馈我觉得是问题的问题
1.当两个存在一个界面的时候,两个光标同事闪烁.是否可以设置初始化的时候弹不弹键盘.
2.当我有用到iqkeyboardmanager的时候,配合你的工具,界面的子视图会到处飞

**Comment by BearRan** [comment]
增加了新方法，
装载：`[boxInputView loadAndPrepareViewWithBeginEdit:NO];`
清空：`[boxInputView clearAllWithBeginEdit:NO];`
可以自己设置是否需要开始编辑状态。
更新到0.1.4版本即可。

**Comment by crazypoo** [comment]
你好,我又来反馈问题了,当你的pod更新的时候,直接更新没有更新到,并且指定版本也不行,一定要pod repo update才行,你可以看看是什么情况

**Comment by BearRan** [comment]
哈喽，我创建pod的过程，好像少了`pod repo push`这一步。所以造成你无法安装。
我弄了个新的版本，0.1.5。你可以把你项目中的podfile.lock删一下，然后不要指定版本号，直接用pod 'CRBoxInputView'，去安装。
如果能直接安装到0.1.5的版本。说明这个问题就解决了，你也和我说一下。如果还是不行，你再帮我open这个issue，我来继续解决。
