### ISSUE TITLE
佬板敢不敢支持pod 1.7.0+

### ISSUE THREAD

**Issue by crazypoo** [CRAnimation/CRBoxInputView#9]
如题,由于最近cocoapods更新了重要的功能版本,但是发现此工具导入的masroy没有引用为#import <xxxxxx/xxxxxx.h>的格式而是#import "xxxxxx.h"的格式,导致须要更改pod文件,望开发者有一个良好的开发习惯.

**Comment by BearRan** [comment]
已经修改为<>引用。请使用0.1.9版本。开发习惯不规范实感惭愧，感谢提醒！
